name: Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: getting the code
        uses: actions/checkout@v3
      - name: setting up a cache
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: installing dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:XYZ
      - name: Run tests
        run: npm test
      - name: get output information
        run: echo "..."
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Get output information
        run: |
          echo "..."